# Generated by Django 5.2.7 on 2025-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skillcategory_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
