# Generated by Django 5.2.7 on 2025-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_contact_github_alter_contact_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='profile_photos'),
            preserve_default=False,
        ),
    ]
