# Generated by Django 5.0.14 on 2025-10-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_title_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='theme',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
