# Generated by Django 5.0.14 on 2025-11-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_title_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
