# Generated by Django 5.0.14 on 2025-11-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_title_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
