# Generated by Django 5.2.7 on 2025-11-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
    ]
