# Generated by Django 5.2.7 on 2025-11-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_title_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='theme',
            field=models.IntegerField(default=1),
        ),
    ]
